language: objective-c
osx_image: xcode7.2
xcode_scheme: NumeroUI
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    # Build for iOS
    - DESTINATION="OS=9.1,name=iPhone 6" SCHEME="NumeroUI" SDK=iphonesimulator9.2 RUN_TESTS="YES"
    - DESTINATION="OS=9.0,name=iPad 2" SCHEME="NumeroUI" SDK=iphonesimulator9.2 RUN_TESTS="YES"

    # Build for watchOS
#   - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="NumeroUI watchOS" SDK=watchsimulator2.0 RUN_TESTS="NO"

    # Build for tvOS
#   - DESTINATION="OS=9.0,name=Apple TV 1080p" SCHEME="NumeroUI tvOS" SDK=appletvsimulator9.0 RUN_TESTS="YES"
before_install:
  - brew update
  - brew install carthage

  - gem update xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

  - carthage bootstrap --no-use-binaries --verbose
script:
  - set -o pipefail
  - xcodebuild -version

  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project NumeroUI.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO test | xcpretty -c -f `xcpretty-travis-formatter`;
    else
      xcodebuild -project NumeroUI.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c -f `xcpretty-travis-formatter`;
    fi
